CARDS = [
("why", "Why does this exist", "Why does an operating system exist at all?", "Because a processor executes one instruction stream with total obedience and no ability to notice a better use of its time, and because that machine has to be shared safely by many programs and many people. Every mechanism in it — privilege, interrupts, virtual memory, scheduling, file descriptors, namespaces — is an answer to some version of that. The economics were visible in the 1950s: the machine cost a fortune and sat idle while a human walked across a room."),
("why", "Why does this exist", "Why can't protection be done in software?", "Because whatever check you write runs as instructions the offending program could jump past, overwrite, or simply never call. A guard the guarded party can remove is not a guard. That is why the mode bit is in the processor and why the page table root register is privileged — and it is also why WebAssembly bounds-checks in the runtime rather than trusting the module, and why eBPF has a verifier."),
("why", "Why does this exist", "Why is the kernel not a process?", "Because it is a mode, not a program with its own schedule. There is one processor executing one stream; when your program traps or a device interrupts, the same processor flips the privilege bit and executes kernel code on your process's time. That is why <code>sy</code> time in <code>top</code> is charged to your process, why <code>process.cpuUsage()</code> reports user and system separately, and why a kernel bug panics the machine instead of killing a process."),
("why", "Why does this exist", "Why did Unix split fork and exec?", "Because the interval between them is a place where the child can adjust itself using ordinary calls — redirect descriptors, drop privileges, change directory, join namespaces — before the new program starts. Shell redirection, pipes, and every container runtime's setup step live in that gap and needed no special API for it. Windows made the opposite choice with a single CreateProcess taking ten arguments."),
("why", "Why does this exist", "Why is everything a file in Unix?", "Because a uniform interface means a tool written for files works on devices, pipes, sockets and kernel state with no special support. It is why <code>cat</code>, redirection and your language's file API all work on <code>/proc</code>, and why every Linux diagnostic tool is ultimately a text parser. It is the earliest example in this material of an interface paying for itself over fifty years."),
("why", "Why does this exist", "Why is the syscall interface Linux's stable ABI rather than the C library?", "Because Torvalds's rule is that userspace never breaks: internal APIs change freely between versions, but syscall number 1 is still write with the same three arguments as it was in 2005. That is why a statically linked Go binary works in a FROM scratch container. Windows made the opposite choice — its syscall numbers change between builds and the stable contract is ntdll.dll."),
("why", "Why does this exist", "Why does virtual memory use fixed-size pages instead of variable-size regions?", "Because variable-size regions fragment: free memory exists but not in a usable shape, and compacting means copying gigabytes while processes are stopped. Fixed-size pages mean any free frame is as good as any other, so external fragmentation disappears entirely — you only waste the tail of the last page. It also makes translation an array index rather than a search."),
("why", "Why does this exist", "Why does the event loop exist when threads already solved concurrency?", "Because threads solved it at a cost that stops scaling. At ten thousand mostly-idle connections you are paying about 100 KB and a full context switch per event, and the caches never hold anything useful. One thread that can wait on all of them replaces the switch with a function call. Go and Java's virtual threads reach the same place from the other direction — they hide an event loop inside the runtime so you can keep writing blocking-style code."),
("why", "Why does this exist", "Why do containers exist when VMs already isolated things?", "Density and start time. A VM carries its own kernel and boots, so it costs seconds and a kernel's worth of memory; a container is a process, so it costs milliseconds and a process. Every kernel feature Docker used already existed — namespaces from 2002, cgroups from 2008 — and Docker's actual contribution in 2013 was the image format, the registry and the developer experience."),
("why", "Why does this exist", "Why does fsync exist rather than write just being durable?", "Because making every write wait for the disk would make everything unusably slow — a commit would cost milliseconds instead of microseconds. So <code>write</code> returns as soon as the bytes are in the page cache, and durability is an explicit, separately-priced operation. Every database configuration knob about durability is a decision about how often to pay it."),
("why", "Why does this exist", "Why does Linux overcommit memory?", "Because fork plus copy-on-write hands out address space that will almost never be realised, and programs routinely reserve large sparse regions they never touch — V8 among them. Refusing those would waste enormous amounts of memory. The consequence is that the debt comes due at a page fault with no sensible failure path, which is why the OOM killer exists and why it uses SIGKILL."),
("why", "Why does this exist", "Why is there a TIME_WAIT state at all?", "Two reasons, both real. A delayed duplicate packet from the old connection must not be delivered to a new connection reusing the same four-tuple. And if the final ACK is lost, the peer will retransmit its FIN and someone has to be there to answer it. Sixty seconds on Linux, and the reason connection pooling matters more than people expect."),
]
